### ISSUE TITLE
Service page tab menu has an issue

### ISSUE THREAD

**Issue by abbasdawood** [dhruvinsanghvi/univibe-corporate#2]
Tabbed menu switches position on getting affixed, is bootstrap affix being used? Suggest that you use the same. Also, all of the tab containers and the tabs themselves must be stored in a row spanning 12 columns, right now the edge-to-edge thing is killing the look of the site.

In the mobile layout, the tab is currently stacking over one another, need custom css to override default BS behavior

**Comment by dhruvinsanghvi** [comment]
tab menu does not switch the position now on getting affixed. I have used affix in main.js refer services.html for this functionality. I have also integrated scrollspy in services page please check services.html. 

Issue which i am facing in scroll spy is that when i click a tab my section starts after some pixel it does not start at the start of that section i am trying to resolve that bug.

In mobile layout tab are now next to each other as we discuss.

**Comment by abbasdawood** [comment]
Please share the comments in the proper format
